# type: ignore

"""delete project name_type_unique constraint

Revision ID: d39d86933ca2
Revises: caac9aa7801a
Create Date: 2025-09-05 14:35:57.034528

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import app


# revision identifiers, used by Alembic.
revision = 'd39d86933ca2'
down_revision = 'caac9aa7801a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name_type_unique_constraint', table_name='project')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name_type_unique_constraint', 'project', ['name', 'type'], unique=True)
    # ### end Alembic commands ###
