# type: ignore

"""alter agentseting records table add agent_type column

Revision ID: 439a5a6330c8
Revises: eae561962ff3
Create Date: 2025-08-12 18:38:57.859066

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import app


# revision identifiers, used by Alembic.
revision = '439a5a6330c8'
down_revision = 'eae561962ff3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agentsettingdebugrecord', sa.Column('agent_type', sa.Enum('transmission', 'substation', 'distribute', 'assistant', name='agenttype'), server_default='assistant',  nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agentsettingdebugrecord', 'agent_type')
    # ### end Alembic commands ###
