# type: ignore

"""add setting proj_type field

Revision ID: 4b30608047a9
Revises: c67bae9a252e
Create Date: 2025-08-11 18:06:32.125337

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import app


# revision identifiers, used by Alembic.
revision = '4b30608047a9'
down_revision = 'c67bae9a252e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agentsetting', sa.Column('agent_type', sa.Enum('transmission', 'substation', 'distribute', 'assistant', name='agenttype'), server_default='assistant', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agentsetting', 'agent_type')
    # ### end Alembic commands ###
