# type: ignore

"""alter agentseting table

Revision ID: 55f6f8a8f9c1
Revises: 4b30608047a9
Create Date: 2025-08-12 18:25:45.674475

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import app
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '55f6f8a8f9c1'
down_revision = '4b30608047a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agentsetting', sa.Column('section', sa.Enum('one', 'two', 'three', 'four', 'five', 'six', 'sevenone', 'seventwo', 'seventhree', 'sevenfour', 'eight', 'nine', 'ten', 'assistant', name='forsection'), nullable=False))
    op.add_column('agentsetting', sa.Column('is_enable', sa.Boolean(), nullable=False))
    op.drop_column('agentsetting', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agentsetting', sa.Column('category', mysql.ENUM('section_detail', 'section_overview', 'document_overview', 'assistant_qa'), nullable=False))
    op.drop_column('agentsetting', 'is_enable')
    op.drop_column('agentsetting', 'section')
    # ### end Alembic commands ###
