# type: ignore

"""add review reference field

Revision ID: 73f0c6b6e38f
Revises: fb3508274fc8
Create Date: 2025-07-17 09:25:50.054404

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import app
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '73f0c6b6e38f'
down_revision = 'fb3508274fc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentcontentreview', sa.Column('reference_filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('documentcontentreview', sa.Column('reference_content', mysql.MEDIUMTEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documentcontentreview', 'reference_content')
    op.drop_column('documentcontentreview', 'reference_filename')
    # ### end Alembic commands ###
