# type: ignore

"""agentsettings add risk_types fields

Revision ID: a6053f46a6a5
Revises: 439a5a6330c8
Create Date: 2025-08-21 10:59:13.433388

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import app
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a6053f46a6a5'
down_revision = '439a5a6330c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agentsetting', sa.Column('risk_types', mysql.MEDIUMTEXT(), nullable=True))
    op.add_column('agentsetting', sa.Column('ref_docs', mysql.MEDIUMTEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agentsetting', 'ref_docs')
    op.drop_column('agentsetting', 'risk_types')
    # ### end Alembic commands ###
