# type: ignore

"""add setting debug records table

Revision ID: c67bae9a252e
Revises: 73f0c6b6e38f
Create Date: 2025-08-08 09:34:50.346505

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import app
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c67bae9a252e'
down_revision = '73f0c6b6e38f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agentsettingdebugrecord',
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocol', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('host', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('app_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('agent_code', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('agent_version', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('category', sa.Enum('section_detail', 'section_overview', 'document_overview', 'assistant_qa', name='agentcategory'), nullable=False),
    sa.Column('req_begin_at', sa.DateTime(), nullable=False),
    sa.Column('req_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('req_header', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('req_payload', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('resp_done_at', sa.DateTime(), nullable=True),
    sa.Column('resp_status', sa.Integer(), nullable=True),
    sa.Column('resp_spend', sa.Float(), nullable=False),
    sa.Column('resp_header', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('resp_text', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('resp_res_text', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('resp_res_json', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('resp_can_validate', sa.Boolean(), nullable=False),
    sa.Column('error_traceback', mysql.MEDIUMTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agentsettingdebugrecord')
    # ### end Alembic commands ###
