# type: ignore

"""alter agentseting debug records table

Revision ID: eae561962ff3
Revises: 55f6f8a8f9c1
Create Date: 2025-08-12 18:31:50.665532

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import app
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eae561962ff3'
down_revision = '55f6f8a8f9c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agentsettingdebugrecord', sa.Column('section', sa.Enum('one', 'two', 'three', 'four', 'five', 'six', 'sevenone', 'seventwo', 'seventhree', 'sevenfour', 'eight', 'nine', 'ten', 'assistant', name='forsection'), server_default='assistant', nullable=False))
    op.drop_column('agentsettingdebugrecord', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agentsettingdebugrecord', sa.Column('category', mysql.ENUM('section_detail', 'section_overview', 'document_overview', 'assistant_qa'), nullable=False))
    op.drop_column('agentsettingdebugrecord', 'section')
    # ### end Alembic commands ###
