# type: ignore

"""docuementcontentreview add ref_docs fields

Revision ID: eef8805e44ed
Revises: a6053f46a6a5
Create Date: 2025-08-21 15:06:19.660148

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import app
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eef8805e44ed'
down_revision = 'a6053f46a6a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentcontentreview', sa.Column('reference_location', mysql.MEDIUMTEXT(), nullable=True))
    op.add_column('documentcontentreview', sa.Column('source_text', mysql.MEDIUMTEXT(), nullable=True))
    op.add_column('documentcontentreview', sa.Column('source_location', mysql.MEDIUMTEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documentcontentreview', 'source_location')
    op.drop_column('documentcontentreview', 'source_text')
    op.drop_column('documentcontentreview', 'reference_location')
    # ### end Alembic commands ###
