# type: ignore

"""init tables

Revision ID: fb3508274fc8
Revises: 
Create Date: 2025-07-10 10:26:14.891982

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import app
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fb3508274fc8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agentsetting',
    sa.Column('protocol', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('host', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('app_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('agent_code', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('agent_version', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('category', sa.Enum('section_detail', 'section_overview', 'document_overview', 'assistant_qa', name='agentcategory'), nullable=False),
    sa.Column('desc', mysql.MEDIUMTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iscuser',
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('orgId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chatsession',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('iscuser_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['iscuser_id'], ['iscuser.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parsedfile',
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('file_suffix', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('save_type', sa.Enum('LOCAL', 'OSS', name='savetype'), nullable=False),
    sa.Column('save_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('iscuser_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('html_content', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('md_content', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('txt_content', mysql.MEDIUMTEXT(), nullable=False),
    sa.ForeignKeyConstraint(['iscuser_id'], ['iscuser.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('type', sa.Enum('TRNAS', 'SUBSTATION', 'DISTRIBUTION', name='projecttypeenum'), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('iscuser_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('review_status', sa.Enum('UNREVIEWED', 'AI_REVIEW_FAILURE', 'AI_REVIEW_NOTPASS', 'AI_REVIEW_PASSED', 'HUMAN_REVIEW_FAILD', 'HUMAN_REVIEW_PASSED', name='reviewstatus'), nullable=False),
    sa.Column('review_percent', sa.Float(), nullable=False),
    sa.Column('review_begin_at', sa.DateTime(), nullable=True),
    sa.Column('review_done_at', sa.DateTime(), nullable=True),
    sa.Column('review_suggestion', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('audit_feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['iscuser_id'], ['iscuser.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'type', name='name_type_unique_constraint')
    )
    op.create_table('chat',
    sa.Column('question', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('iscuser_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('answer', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('answer_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['iscuser_id'], ['iscuser.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['chatsession.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document',
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('file_suffix', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_category', sa.Enum('THREESTEP', 'METTING', 'FEASIBIBITY', 'SURVEY', 'OTHER', name='filecategory'), nullable=False),
    sa.Column('save_type', sa.Enum('LOCAL', 'OSS', name='savetype'), nullable=False),
    sa.Column('save_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('iscuser_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('proj_id', sa.Uuid(), nullable=False),
    sa.Column('proj_version', sa.Integer(), nullable=False),
    sa.Column('review_status', sa.Enum('UNREVIEWED', 'AI_REVIEW_FAILURE', 'AI_REVIEW_NOTPASS', 'AI_REVIEW_PASSED', 'HUMAN_REVIEW_FAILD', 'HUMAN_REVIEW_PASSED', name='reviewstatus'), nullable=False),
    sa.Column('review_percent', sa.Float(), nullable=False),
    sa.Column('review_begin_at', sa.DateTime(), nullable=True),
    sa.Column('review_done_at', sa.DateTime(), nullable=True),
    sa.Column('review_suggestion', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['iscuser_id'], ['iscuser.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proj_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentcontent',
    sa.Column('section', sa.Enum('all', 'head', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', name='sectiontype'), nullable=False),
    sa.Column('content', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('suggestion', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('iscuser_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('proj_id', sa.Uuid(), nullable=False),
    sa.Column('proj_version', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['document.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['iscuser_id'], ['iscuser.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proj_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentcontentreview',
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('iscuser_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('proj_id', sa.Uuid(), nullable=False),
    sa.Column('proj_version', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Uuid(), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('section', sa.Enum('all', 'head', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', name='sectiontype'), nullable=False),
    sa.Column('question', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('question_tag', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('feedback', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('feedback_tag', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('ai_error', mysql.MEDIUMTEXT(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['documentcontent.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doc_id'], ['document.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['iscuser_id'], ['iscuser.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proj_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documentcontentreview')
    op.drop_table('documentcontent')
    op.drop_table('document')
    op.drop_table('chat')
    op.drop_table('project')
    op.drop_table('parsedfile')
    op.drop_table('chatsession')
    op.drop_table('iscuser')
    op.drop_table('agentsetting')
    # ### end Alembic commands ###
